---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduit-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: rook-ceph-block
