---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2
    env:
      TZ: "America/Chicago"
    service:
      bittorrent:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_QBIT_IP}
        externalTrafficPolicy: Local
        ports:
          bittorrent:
            enabled: true
            port: 50413
            protocol: TCP
            targetPort: 50413
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "pirate"
          hajimari.io/instance: "internal"
          hajimari.io/group: "Media"
        hosts:
          - host: "qbit.k.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qbit.k.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config
      media:
        enabled: true
        readOnly: false
        mountPath: /nfs-media
        existingClaim: nfs-media-pvc
    podAnnotations:
      backup.velero.io/backup-volumes: config
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 2000Mi
