---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.1.0.6175
    env:
      TZ: "America/Chicago"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-internal
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 5m
          hajimari.io/enable: "true"
          hajimari.io/icon: "movie-search"
          hajimari.io/instance: "internal"
          hajimari.io/group: "Media"
        hosts:
          - host: "radarr.k.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "radarr.k.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
      media:
        enabled: true
        readOnly: false
        existingClaim: nfs-media-pvc
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    podAnnotations:
      backup.velero.io/backup-volumes: config
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1000Mi
    tolerations:
      - key: "arm"
        operator: "Exists"
