---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onedrive
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: onedrive
      version: 2.3.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: driveone/onedrive
      tag: 2.4.20
      pullPolicy: IfNotPresent
    env:
      TZ: America/Chicago
      ONEDRIVE_DOWNLOADONLY: 1
      ONEDRIVE_AUTHRESPONSE: "${SECRET_ONEDRIVE_AUTHRESPONSE}"
    persistence:
      config:
        storageClass: "rook-ceph-block"
        size: 1Gi
      data:
        existingClaim: nfs-onedrive-pvc
    podAnnotations:
      backup.velero.io/backup-volumes: config
