---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onedrive-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
