---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.22.3.4523-d0ce30438
    env:
      TZ: "America/Chicago"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${SVC_PLEX_IP}
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: plex
    ingress:
      main:
        enabled: true
        ingressClassName: nginx-external
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          hajimari.io/enable: "true"
          hajimari.io/icon: "plex"
          hajimari.io/instance: "internal"
          hajimari.io/group: "Media"
        hosts:
          - host: "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${SECRET_DOMAIN}"
            secretName: plex-cert-external
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
      media:
        enabled: true
        readOnly: true
        mountPath: /data
        existingClaim: nfs-media-pvc
    podAnnotations:
      backup.velero.io/backup-volumes: config
