---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dendrite
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: dendrite
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: wrmilling-charts
        namespace: flux-system
  values:
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/tls-acme: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/custom-http-errors: "418"
          nginx.ingress.kubernetes.io/default-backend: "dendrite"
        hosts:
          - host: dendrite.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: nginx-external
        tls:
          - secretName: conduit-cert
            hosts:
              - dendrite.${SECRET_DOMAIN}
    persistence:
      media:
        enabled: true
        existingClaim: dendrite-media-pvc
      jetstream:
        enabled: true
        existingClaim: dendrite-jetstream-pvc
    dendrite:
      polylithEnabled: false
      matrix_key_secret:
        existingSecret: dendrite-matrix-key
      global:
        server_name: ${SECRET_DOMAIN_SECONDARY}
        well_known_server_name: dendrite.${SECRET_DOMAIN}:443
    clientapi:
      config:
        registration_disabled: true
        registration_shared_secret: ${SECRET_DENDRITE_REGISTRATION_SECRET}
    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: "dendrite-postgres-pvc"
      auth:
        username: dendrite
        database: dendrite
        password: ${SECRET_DENDRITE_POSTGRES_PASSWORD}
        postgresPassword: ${SECRET_DENDRITE_POSTGRES_POSTGRES_PASSWORD}
