---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-tailscale
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      hostname: "ingress-tailscale"
      ingressClass: nginx-tailscale
      ingressClassByName: true
      ingressClassResource:
        name: nginx-tailscale
        enabled: true
        default: false
        controllerValue: "k8s.io/ingress-nginx-tailscale"
      admissionWebhooks:
        objectSelector:
          matchExpressions:
            - key: ingress-class
              operator: In
              values:
                - nginx-tailscale
      replicaCount: 1
      config:
        custom-http-errors: 404,401,403,500,503
        hsts-max-age: "31449600"
      use-forwarded-headers: "true"
      service:
        type: ClusterIP
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
        prometheusRule:
          enabled: false
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret"
      resources:
        requests:
          memory: 500Mi
          cpu: 25m
        limits:
          memory: 600Mi
      extraContainers:
        - name: tailscaled
          image: ghcr.io/tailscale/tailscale:latest
          imagePullPolicy: Always
          env:
          - name: TS_KUBE_SECRET
            value: tailscale
          - name: TS_USERSPACE
            value: "false"
          - name: TS_AUTH_KEY
            value: ${SECRET_TAILSCALE_AUTH_KEY}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi

