---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    configInline:
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 10.10.40.60-10.10.40.99
    prometheusRule:
      enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    controller:
      tolerations:
      - key: "arm"
        operator: "Exists"
    speaker:
      tolerations:
      - key: "arm"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
